language: go
sudo: false

before_install:
  - git config --global user.name "TravisCI"

install:
  go get -d -t -v ./... && go build -v ./...

go:
  - 1.4
  - 1.5

env:
  - GOMAXPROCS=4

script: ./scripts/run_build.sh
